# Generated by Django 5.1.7 on 2025-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ubicacionUser',
            field=models.TextField(blank=True, null=True),
        ),
    ]
