# Generated by Django 5.1.7 on 2025-06-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pdf', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
