# Generated by Django 5.1.7 on 2025-07-08 01:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_historicalcategorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nameFurniture', models.CharField(max_length=100)),
                ('descriptionFurniture', models.CharField(max_length=1500)),
                ('priceFurniture', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentajeDescuento', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('stateFurniture', models.BooleanField(default=True)),
                ('imageFurniture', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userID', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical productos',
                'verbose_name_plural': 'historical productoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFurniture', models.CharField(max_length=100)),
                ('descriptionFurniture', models.CharField(max_length=1500)),
                ('priceFurniture', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentajeDescuento', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('stateFurniture', models.BooleanField(default=True)),
                ('imageFurniture', models.TextField(blank=True, null=True)),
                ('categoryID', models.ManyToManyField(related_name='productos', to='categorias.categorias')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
