# Generated by Django 5.1.7 on 2025-06-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField(default=list)),
                ('phones', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('socials', models.JSONField(default=dict)),
            ],
        ),
    ]
