# Generated by Django 5.1.7 on 2025-07-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='ubicacion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
